# Change these first
owner: tinsever # Your GitHub organization or username, where this repository lives
repo: upptime-mn # The name of this repository

sites:
  - name: FOREX-Börse
    url: https://fin.mn-netz.de
  - name: NETZ-API
    url: https://api.mn-netz.de
  - name: NETZ-Dashboard
    url: https://dash.mn-netz.de
  - name: Konferenz der Nationen
    url: https://rdn.mn-netz.de
  - name: Marktplatz
    url: https://mn-marktplatz.de
  - name: Wiki
    url: https://mn-wiki.de

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.mn-netz.de
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Netz-Status
  introTitle: "**Netz-Status** ist eine Statusseite für die Mikronationen."
  introMessage: Die ersten vier Seiten werden von uns, mir, betrieben!
  navbar:
    - title: Status
      href: /
    - title: Zur Börse
      href: https://fin.mn-netz.de

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
